#pragma once

#define SHARPGUI_INCLUDE_DX9		1
#define SHARPGUI_INCLUDE_DX10		1
#define SHARPGUI_INCLUDE_DX11		1
#define SHARPGUI_INCLUDE_DX12		1
#define SHARPGUI_INCLUDE_OVERLAY	1

#define SHARPGUI_INCLUDE_OPENGL		1

#if SHARPGUI_INCLUDE_DX9
#define KIERO_INCLUDE_D3D9 1
#endif

#if SHARPGUI_INCLUDE_DX10
#define KIERO_INCLUDE_D3D10 1
#endif

#if SHARPGUI_INCLUDE_DX11
#define KIERO_INCLUDE_D3D11 1
#endif

#if SHARPGUI_INCLUDE_DX12
#define KIERO_INCLUDE_D3D12 1
#endif

#if SHARPGUI_INCLUDE_OPENGL
#define KIERO_INCLUDE_OPENGL 1
#endif
